name: helm package
description: Packs the helm chart and optionally signs it
inputs:
  chartName:
    default: durabletask-azurestorage-scaler
    description: The name of the Helm chart
    required: false
  chartPath:
    description: The path to the Helm chart
    required: true
  chartVersion:
    description: The version of the Helm chart
    required: true
  gpgPassword:
    default: ''
    description: The password for the GPG key
    required: false
  gpgPrivateKey:
    default: ''
    description: The Base64 GPG private signing key
    required: false
  sign:
    default: 'false'
    description: Indicates whether the helm chart should be signed
    required: false

runs:
  using: composite
  steps:
    - name: Create Chart Folder
      shell: bash
      run: mkdir -p ${{ runner.temp }}/chart

    - name: Create Keyring
      shell: bash
      if: ${{ inputs.sign == 'true' }}
      run: |
        mkdir -p ${{ runner.temp }}/gpg
        echo '${{ inputs.gpgPrivateKey }}' | base64 --decode >> ${{ runner.temp }}/gpg/private-key.gpg

    - name: Helm Pack with Signing
      shell: bash
      if: ${{ inputs.sign == 'true' }}
      run: echo "${{ inputs.gpgPassword }}" | helm package ${{ inputs.chartPath }} --sign --key 'Will Sugarman' --keyring ${{ runner.temp }}/gpg/private-key.gpg --passphrase-file -
      working-directory: ${{ runner.temp }}/chart

    - name: Helm Pack
      shell: bash
      if: ${{ inputs.sign != 'true' }}
      run: helm package ${{ inputs.chartPath }}
      working-directory: ${{ runner.temp }}/chart

    - name: Delete Keyring
      shell: bash
      if: ${{ (inputs.sign == 'true') && always() }}
      run: rm ${{ runner.temp }}/gpg/private-key.gpg

    - name: Upload Chart
      uses: actions/upload-artifact@v3
      with:
        name: chart
        path: ${{ runner.temp }}/chart
