# Default names are derived from the name of the chart
name: ""
fullnameOverride: ""

taskHub:
  name: "TestTaskHub"
  connectionString: ""
  maxActivitiesPerWorker: 2
  maxOrchestrationsPerWorker: 1
  partitionCount: 4

# Docker image metadata
image:
  repository: example-function-app
  tag: ""
  pullPolicy: IfNotPresent

# Metadata concerning how to scale
scaledObject:
  pollingInterval: 5
  cooldownPeriod: 15
  minReplicaCount: 0
  maxReplicaCount: 100

# External scaler information
externalScaler:
  serviceName: durabletask-azurestorage-scaler
  namespace: keda
  port: 4370

# Optional upgrade strategy
upgradeStrategy: {}
  # type: RollingUpdate
  # rollingUpdate:
  #   maxUnavailable: 1
  #   maxSurge: 1

# Container resource requests and limits
resources:
  requests:
    cpu: 100m
    memory: 256M
  limits:
    cpu: '1'
    memory: 1G

# Security context for the scaler container
securityContext:
  capabilities:
    drop:
    - ALL
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  seccompProfile:
    type: RuntimeDefault

# Security context for all containers in the scaler pods
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  # runAsGroup: 2000
  # fsGroup: 2000
