name: Check Code Coverage
description: Validates code coverage and uploads the results.
inputs:
  codecovToken:
    description: The Codecov upload token
    required: true
  reportPath:
    description: The path to the cobertura coverage file.
    required: true
runs:
  using: composite
  steps:
    - name: Copy Code Coverage
      shell: pwsh
      run: |
        New-Item -ItemType 'directory' -Path '${{ runner.temp }}/codecoverage/' | Out-Null
        Copy-Item '${{ inputs.reportPath }}' -Destination '${{ runner.temp }}/codecoverage/'

    - name: Upload Code Coverage Report
      uses: actions/upload-artifact@v3
      with:
        name: coverage
        path: ${{ runner.temp }}/codecoverage

    - name: Codecov Upload
      uses: codecov/codecov-action@v4.0.0-beta.3
      with:
        files: coverage.cobertura.xml
        fail_ci_if_error: true
        token: ${{ inputs.codecovToken }}
        working-directory: ${{ runner.temp }}/codecoverage
        verbose: true
