# Based on https://github.com/Azure/Azurite/issues/968
apiVersion: v1
kind: Namespace
metadata:
  name: azure
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  namespace: azure
spec:
  selector:
    matchLabels:
      component: azurite
  replicas: 1
  template:
    metadata:
      labels:
        component: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:latest
          imagePullPolicy: IfNotPresent
          command:
            - azurite
            - -l
            - /data
            - --blobHost
            - "0.0.0.0"
            - --queueHost
            - "0.0.0.0"
            - --tableHost
            - "0.0.0.0"
            - --loose
          resources:
            limits:
              cpu: "1"
              memory: 1G
            requests:
              cpu: 100m
              memory: 500M
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath:
            path: $PWD/.data/azurite
---
kind: Service
apiVersion: v1
metadata:
  name: azurite
  namespace: azure
spec:
  selector:
    component: azurite
  ports:
    - name: blob
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: queue
      protocol: TCP
      port: 10001
      targetPort: 10001
    - name: table
      protocol: TCP
      port: 10002
      targetPort: 10002
