apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: {{ template "example-function-app.fullname" . }}
    {{- include "example-function-app.labels" . | indent 4 }}
  name: {{ template "example-function-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  host.master: SE9jYnJ4SWc5MGJZcU5NOFNrU0V0a0dtREJYYkVfdmJuVXVFc2g0aUhYR3pBekZ1MjRHNGlRPT0=
  host.function.default: bWlpX2l4aGRWQjFwRmhhM0VQZFV3NjNqYUFBVFBfelB5NS1DbWdnNzFRTHNBekZ1OHFfSWNRPT0=
  host.systemKey.default: N29pekx1SEVkZmM5M20tSWl6X0JZRDVYSEdxSFJrMjZWTnFFYVlJY2UyZ1BBekZ1QnIzRVF3PT0=
  functions.ishealthyasync.default: d0VTYXdvTXVWcVBCQk4xZWxKSFpsQnBJOHN2b0RySHFmS3ZVajdUUjFrQjZBekZ1VXN4b3ZBPT0=
