apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "example-function-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - ''
  resources:
  - secrets
  - configMaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
