apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: {{ template "example-function-app.fullname" . }}
  name: {{ template "example-function-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "example-function-app.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "example-function-app.fullname" . }}
