//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Keda.Scaler.DurableTask.AzureStorage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Keda.Scaler.DurableTask.AzureStorage.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple Azure Storage connection values may not be specified..
        /// </summary>
        internal static string AmbiguousConnection {
            get {
                return ResourceManager.GetString("AmbiguousConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot be empty or white space..
        /// </summary>
        internal static string EmptyOrWhiteSpaceFormat {
            get {
                return ResourceManager.GetString("EmptyOrWhiteSpaceFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find the specified file at &apos;{0}&apos;..
        /// </summary>
        internal static string FileNotFoundFormat {
            get {
                return ResourceManager.GetString("FileNotFoundFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may only be used with identity-based connections..
        /// </summary>
        internal static string IdentityConnectionOnlyPropertyFormat {
            get {
                return ResourceManager.GetString("IdentityConnectionOnlyPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an internal server error. Please check the logs for details and ensure your deployment is correct..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection environment variable &apos;{0}&apos; could not be resolved..
        /// </summary>
        internal static string InvalidConnectionEnvironmentVariableFormat {
            get {
                return ResourceManager.GetString("InvalidConnectionEnvironmentVariableFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected member of type &apos;{0}&apos; but instead found &apos;{1}&apos;..
        /// </summary>
        internal static string InvalidMemberTypeFormat {
            get {
                return ResourceManager.GetString("InvalidMemberTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received unknown gRPC request type..
        /// </summary>
        internal static string InvalidRequestType {
            get {
                return ResourceManager.GetString("InvalidRequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify a custom TLS client certificate issuer if client certificate validation is disabled..
        /// </summary>
        internal static string InvalidTlsClientValidation {
            get {
                return ResourceManager.GetString("InvalidTlsClientValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key was specified without a certificate..
        /// </summary>
        internal static string MissingCertificate {
            get {
                return ResourceManager.GetString("MissingCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managed identity must be enabled when specifying AccountName..
        /// </summary>
        internal static string MissingManagedIdentity {
            get {
                return ResourceManager.GetString("MissingManagedIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing value for member &apos;{0}&apos;..
        /// </summary>
        internal static string MissingMemberFormat {
            get {
                return ResourceManager.GetString("MissingMemberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be specified for private clouds..
        /// </summary>
        internal static string MissingPrivateCloudPropertyFormat {
            get {
                return ResourceManager.GetString("MissingPrivateCloudPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may only be specified for private clouds..
        /// </summary>
        internal static string PrivateCloudOnlyPropertyFormat {
            get {
                return ResourceManager.GetString("PrivateCloudOnlyPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find scaler metadata for current request..
        /// </summary>
        internal static string ScalerMetadataNotFound {
            get {
                return ResourceManager.GetString("ScalerMetadataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may only be specified with an Azure Storage account name..
        /// </summary>
        internal static string ServiceUriOnlyPropertyFormat {
            get {
                return ResourceManager.GetString("ServiceUriOnlyPropertyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cloud &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownCloudValueFormat {
            get {
                return ResourceManager.GetString("UnknownCloudValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown value &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownValueFormat {
            get {
                return ResourceManager.GetString("UnknownValueFormat", resourceCulture);
            }
        }
    }
}
