name: docker test
description: Builds the scaler docker image
inputs:
  imageRepository:
    default: durabletask-azurestorage-scaler
    description: The repository used for the scaler image
    required: false
  imageTag:
    description: The tag to use for the images
    required: true

runs:
  using: composite
  steps:
    - name: Download Scaler Binaries
      uses: actions/download-artifact@v3
      with:
        name: app
        path: ${{ runner.temp }}/app

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Generate OCI Labels
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.imageRepository }}
        tags: |
          type=semver,pattern={{version}},value=v${{ inputs.imageTag }}

    - name: Build Scaler Image
      uses: docker/build-push-action@v4
      with:
        build-args: |
          COPY=true
          PUBLISH_DIRECTORY=${{ runner.temp }}/app
        context: .
        file: ./src/Keda.Scaler.DurableTask.AzureStorage/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}

    - name: Save Image
      shell: bash
      run: |
        output="${{ runner.temp }}/image/durabletask-azurestorage-scaler-${{ inputs.imageTag }}.tar"
        mkdir -p $(dirname $output)
        docker save -o $output ${{ inputs.imageRepository }}:${{ inputs.imageTag }}

    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: ${{ runner.temp }}/image/durabletask-azurestorage-scaler-${{ inputs.imageTag }}.tar
