name: docker test
description: Builds the scaler docker image
inputs:
  assemblyVersion:
    description: The resulting assembly's version
    required: true
  buildConfiguration:
    default: Debug
    description: The dotnet build configuration
    required: false
  fileVersion:
    description: The resulting assembly's file version
    required: true
  imageRepository:
    default: durabletask-azurestorage-scaler
    description: The repository used for the scaler image
    required: false
  imageTag:
    description: The tag to use for the images
    required: true

runs:
  using: composite
  steps:
    - name: Generate OCI Labels
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.imageRepository }}
        tags: |
          type=semver,pattern={{version}},value=v${{ inputs.imageTag }}

    - name: Build Scaler Image
      uses: docker/build-push-action@v3
      with:
        build-args: |
          ASSEMBLY_VERSION=${{ inputs.assemblyVersion }}
          BUILD_CONFIGURATION=${{ inputs.buildConfiguration }}
          CONTINUOUS_INTEGRATION_BUILD=true
          FILE_VERSION=${{ inputs.fileVersion }}
        context: .
        file: ./src/Keda.Scaler.DurableTask.AzureStorage/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}

    - name: Save Image
      shell: bash
      run: |
        output="${{ runner.temp }}/docker/durabletask-azurestorage-scaler-${{ inputs.imageTag }}.tar"

        mkdir -p $(dirname $output)
        docker save -o $output ${{ inputs.imageRepository }}:${{ inputs.imageTag }}

    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: ${{ runner.temp }}/docker/durabletask-azurestorage-scaler-${{ inputs.imageTag }}.tar
