name: docker test
description: Builds the scaler docker image
inputs:
  assemblyVersion:
    description: The resulting assembly's version
    required: true
  buildConfiguration:
    default: Debug
    description: The dotnet build configuration
    required: false
  fileVersion:
    description: The resulting assembly's file version
    required: true
  imageRepository:
    default: durabletask-azurestorage-scaler
    description: The repository used for the scaler image
    required: false
  imageTag:
    description: The tag to use for the images
    required: true

runs:
  using: composite
  steps:
    - name: Build Scaler Image
      shell: bash
      run: |
        docker build \
          --build-arg BUILD_CONFIGURATION=${{ inputs.buildConfiguration }} \
          --build-arg CONTINUOUS_INTEGRATION_BUILD=true \
          --build-arg ASSEMBLY_VERSION=${{ inputs.assemblyVersion }} \
          --build-arg FILE_VERSION=${{ inputs.fileVersion }} \
          -f ./src/Keda.Scaler.DurableTask.AzureStorage/Dockerfile \
          -t ${{ inputs.imageRepository }}:${{ inputs.imageTag }} \
          .

    - name: Save Image
      id: save
      shell: bash
      run: |
        repository="${{ inputs.imageRepository }}"
        name=${repository#*/}
        output="${{ runner.temp }}/docker/$name-${{ inputs.imageTag }}.tar"

        mkdir -p $(dirname $output)
        docker save -o $output ${{ inputs.imageRepository }}:${{ inputs.imageTag }}
        echo "path=$output" >> $GITHUB_OUTPUT

    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: ${{ steps.save.outputs.path }}
