name: docker test
description: Builds the scaler docker image
inputs:
  assemblyVersion:
    default: '1.0.0'
    description: The scaler assembly's version.
    required: false
  buildConfiguration:
    default: Debug
    description: The dotnet build configuration.
    required: false
  copyBinaries:
    default: 'false'
    description: Indicates whether the dockerfile should build the scaler or simply copy existing binaries.
    required: false
  fileVersion:
    default: '1.0.0'
    description: The scaler assembly's file version.
    required: false
  imageRepository:
    default: durabletask-azurestorage-scaler
    description: The repository used for the scaler image.
    required: false
  imageTag:
    description: The tag to use for the images.
    required: true

runs:
  using: composite
  steps:
    - if: ${{ inputs.copyBinaries == 'true' }}
      name: Download Scaler Binaries
      uses: actions/download-artifact@v3
      with:
        name: app
        path: ./app

    - name: Generate OCI Labels
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ${{ inputs.imageRepository }}
        tags: |
          type=semver,pattern={{version}},value=v${{ inputs.imageTag }}

    - name: Build Scaler Image
      uses: docker/build-push-action@v4
      with:
        build-args: |
          ASSEMBLY_VERSION=${{ inputs.assemblyVersion }}
          BUILD_CONFIGURATION=${{ inputs.buildConfiguration }}
          CONTINUOUS_INTEGRATION_BUILD=true
          COPY=${{ inputs.copyBinaries }}
          FILE_VERSION=${{ inputs.fileVersion }}
          PUBLISH_DIRECTORY=./app
        context: .
        file: ./src/Keda.Scaler.DurableTask.AzureStorage/Dockerfile
        labels: ${{ steps.meta.outputs.labels }}
        push: false
        tags: ${{ steps.meta.outputs.tags }}

    - name: Save Image
      shell: bash
      run: |
        output="${{ runner.temp }}/image/durabletask-azurestorage-scaler-${{ inputs.imageTag }}.tar"
        mkdir -p $(dirname $output)
        docker save -o $output ${{ inputs.imageRepository }}:${{ inputs.imageTag }}

    - name: Upload Image
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: ${{ runner.temp }}/image/durabletask-azurestorage-scaler-${{ inputs.imageTag }}.tar
