{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: {{ template "durabletask-azurestorage-scaler.serviceAccountName" . }}
    {{- if .Values.podIdentity.azureWorkload.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
    {{- include "durabletask-azurestorage-scaler.labels" . | indent 4 }}
  {{- if or .Values.podIdentity.azureWorkload.enabled .Values.serviceAccount.annotations .Values.additionalAnnotations }}
  annotations:
    {{- if .Values.additionalAnnotations }}
    {{- toYaml .Values.additionalAnnotations | indent 4 }}
    {{- end }}
    {{- if .Values.podIdentity.azureWorkload.enabled }}
    {{- if .Values.podIdentity.azureWorkload.clientId }}
    azure.workload.identity/client-id: {{ .Values.podIdentity.azureWorkload.clientId | quote }}
    {{- end }}
    {{- if .Values.podIdentity.azureWorkload.tenantId }}
    azure.workload.identity/tenant-id: {{ .Values.podIdentity.azureWorkload.tenantId | quote }}
    {{- end }}
    azure.workload.identity/service-account-token-expiration: {{ .Values.podIdentity.azureWorkload.tokenExpiration | quote }}
    {{- end }}
    {{- if .Values.serviceAccount.annotations }}
    {{- toYaml .Values.serviceAccount.annotations | nindent 4}}
    {{- end }}
  {{- end }}
  name: {{ template "durabletask-azurestorage-scaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end -}}
