{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "durabletask-azurestorage-external-scaler.fullname" . }}
  labels:
    {{- include "durabletask-azurestorage-external-scaler.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "durabletask-azurestorage-external-scaler.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "durabletask-azurestorage-external-scaler.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
