{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "durabletask-azurestorage-external-scaler.fullname" . }}
  labels:
    {{- include "durabletask-azurestorage-external-scaler.labels" . | nindent 4 }}
rules:
- apiGroups:
  - keda.sh
  resources:
  - scaledobjects
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - deployments/scale
  - statefulsets/scale
  verbs:
  - get
{{- end -}}
