name: Scaler Helm

on:
  push:
    branches: [ main ]
    paths:
      - 'charts/releases/**'
      - '!**/artifacthub-repo.yml'

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3